### ISSUE TITLE
Create: Homepage

### ISSUE THREAD

**Issue by kogunlu** [kogunlu/codezillas-capstone#1]
## Summary

We need to create the home page of the website. This will be a "page" container that will have several components inside.

### Screenshots
Here are the 6 screenshots to describe the home page.

1. ![homepage-1](https://user-images.githubusercontent.com/101986399/208870450-5362bbc5-2195-414f-b946-81196a6e6c02.png)
2. ![homepage-2](https://user-images.githubusercontent.com/101986399/208870479-03102e6e-0749-42fa-92f6-0376bd1fc769.png)
3. ![homepage-3](https://user-images.githubusercontent.com/101986399/208870518-a9c375bb-8bb4-4204-9a5a-0694130ed486.png)
4. ![homepage-4](https://user-images.githubusercontent.com/101986399/208870514-ef64aee1-ff58-4a25-97f1-085a1c835e6f.png)
5. ![homepage-5](https://user-images.githubusercontent.com/101986399/208870508-bc13b34c-7c98-414f-94a3-69ebd3cb6763.png)
6. ![homepage-6](https://user-images.githubusercontent.com/101986399/208870504-e4be221c-7c74-41f1-8ed7-0e8d19454a3e.png)

### Constriants / Details
We need to consider which parts will be "shared components" and in which parts we need to use Redux and/or Firabase.

### Subissues to complete

- [x] Navbar
- [x] 1st part => "We are here to help" part
- [x] 2nd part => "Professional..." part
- [x] 3rd part => "We can communicate..." part
- [x] 4th part => "Recent blogs" part
- [x] 5th part => "Purchase tickets" part
- [x] Footer

**Comment by kogunlu** [comment]
I will create separate issues on GitHub project page for this issue.
